// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sauberfix.Data;

#nullable disable

namespace Sauberfix.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sauberfix.Data.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrtId")
                        .HasColumnType("integer");

                    b.Property<string>("Strasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrtId");

                    b.ToTable("Kunden");
                });

            modelBuilder.Entity("Sauberfix.Data.Mitarbeiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mitarbeiter");
                });

            modelBuilder.Entity("Sauberfix.Data.Ort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Plz")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("StadtName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Orte");
                });

            modelBuilder.Entity("Sauberfix.Data.Termin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumUhrzeit")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("ErinnerungVerschickt")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("KundeId")
                        .HasColumnType("integer");

                    b.Property<int?>("MitarbeiterId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.HasIndex("MitarbeiterId");

                    b.ToTable("Termine");
                });

            modelBuilder.Entity("Sauberfix.Data.Kunde", b =>
                {
                    b.HasOne("Sauberfix.Data.Ort", "Ort")
                        .WithMany("Kunden")
                        .HasForeignKey("OrtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ort");
                });

            modelBuilder.Entity("Sauberfix.Data.Termin", b =>
                {
                    b.HasOne("Sauberfix.Data.Kunde", "Kunde")
                        .WithMany("Termine")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sauberfix.Data.Mitarbeiter", "Mitarbeiter")
                        .WithMany("Termine")
                        .HasForeignKey("MitarbeiterId");

                    b.Navigation("Kunde");

                    b.Navigation("Mitarbeiter");
                });

            modelBuilder.Entity("Sauberfix.Data.Kunde", b =>
                {
                    b.Navigation("Termine");
                });

            modelBuilder.Entity("Sauberfix.Data.Mitarbeiter", b =>
                {
                    b.Navigation("Termine");
                });

            modelBuilder.Entity("Sauberfix.Data.Ort", b =>
                {
                    b.Navigation("Kunden");
                });
#pragma warning restore 612, 618
        }
    }
}
